### ISSUE TITLE
Default username and password

### ISSUE THREAD

**Issue by seyo-IV** [sapk/dockerfiles#41]
what is the defaul username and password for your cloud9 docker image. Or how cn i create user for it?

**Comment by sapk** [comment]
Hi,
You can set the username and password via the flag `--auth username:password` in the command part.
Please read the part Usage in https://hub.docker.com/r/sapk/cloud9/ or https://github.com/sapk/dockerfiles/tree/master/cloud9#usage.

**Comment by seyo-IV** [comment]
okay thx it worked :). Can be closed now
