### ISSUE TITLE
After starting container, Terminal console spam

### ISSUE THREAD

**Issue by entmike** [sapk/dockerfiles#42]
Example command:

```bash
docker run -d -v $(pwd)/workspace:/workspace -p 8181:8181 sapk/cloud9 --auth username:password
```

I can log in, but the terminal in Cloud 9 IDE spams the following message:

```bash
tmux: invalid LC_ALL, LC_CTYPE or LANG
tmux: invalid LC_ALL, LC_CTYPE or LANG
tmux: invalid LC_ALL, LC_CTYPE or LANG
tmux: invalid LC_ALL, LC_CTYPE or LANG
...
```

When connecting to the container via bash, I get this warning message:

`bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)`

**Comment by sapk** [comment]
I had to set them to fix the build recently and I removed the deps after the install for clean-up but tmux is used later by web shell. Should be fix by the latest commit. The build on docker hub/cloud should come soon.

**Comment by entmike** [comment]
Wow, that was quick.  Thanks!  I'll keep an eye open for the updated dockerhub build.
